blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Ideas
    url: https://github.com/glowingjade/obsidian-smart-composer/discussions/categories/ideas-feature-requests
    about: Please submit feature requests and ideas in our Discussions section
  - name: General Questions
    url: https://github.com/glowingjade/obsidian-smart-composer/discussions/categories/q-a
    about: Please submit general questions about using Smart Composer in our Discussions section
